USE [SUCOS_VENDAS]
GO
CREATE TABLE TABELA_PRODUTOS (
	[CODIGO DO PRODUTO] [varchar](20) NOT NULL,
	[NOME DO PRODUTO] [varchar](150) NULL,
	[EMBALAGEM] [varchar](50) NULL,
	[TAMANHO] [varchar](50) NULL,
	[SABOR] [varchar](50) NULL,
	[PREÇO DE LISTA] [smallmoney] NULL);

ALTER TABLE [TABELA_PRODUTOS]
ADD CONSTRAINT PK_TABELA_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);

INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1040107', 'Light - 350ml - Melância', 'Lata', '350ml', 'Melância', 4.56);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1000889', 'Sabor da Montanha - 700ml - Uva', 'Garrafa', '700ml', 'Uva', 6.31);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1040327', 'Videira do Campo - 1,5 Litro - Melância', 'PET', '1,5 Litro', 'Melância', 19.51);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('544931', 'Frescor do Verão - 350ml - Limão', 'PET', '350ml', 'Limão', 2.46);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1078680', 'Frescor do Verão - 470ml - Manga', 'Garrafa', '470ml', 'Manga', 5.18);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1042712', 'Linha Citros - 700ml - Limão', 'Garrafa', '700ml', 'Limão', 4.90);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('788975', 'Pedaços de Frutas - 1,5 Litros - Maçã', 'PET', '1,5 Litros', 'Maçã', 18.01);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('1002767', 'Videira do Campo - 700ml - Açai', 'Garrafa', '700ml', 'Açai', 8.41);
INSERT INTO [TABELA_PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]) VALUES ('231776', 'Festival de Sabores - 2 Litros - Açai', 'PET', '2 Litros', 'Açai', 15.18);




