USE [SUCOS_VENDAS]
GO
CREATE TABLE TABELA_VENDEDORES (
	[MATRICULA] [char](5) NOT NULL,
	[NOME] [varchar](100) NULL,
	[PERCENTUAL COMISSÃO] [smallint] NULL);

ALTER TABLE [TABELA_VENDEDORES]
ADD CONSTRAINT PK_TABELA_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA]);

INSERT INTO [TABELA_VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES ('92716', 'Roger da Silva Santos', 5);
INSERT INTO [TABELA_VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES ('14917', 'Barbara Costa Reis', 10);
INSERT INTO [TABELA_VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES ('58313', 'Bruna Gomes Costa', 15);
INSERT INTO [TABELA_VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES ('10981', 'Erick Silva Blass', 10);
INSERT INTO [TABELA_VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES ('58213', 'Ana Julia Bosso', 10);
INSERT INTO [TABELA_VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES ('10213', 'Vinicius Longo da Sila', 20);